---@meta

globals = {}
--#region dofileopt


---<h1><a href="https://premake.github.io/docs/globals/dofileopt">dofileopt</a></h1>
---Find and execute a Lua source file, but continue without error if the file is not present.
---
--[[
```lua
dofileopt("filename")
```
]]
---
---
---@param filename string `fname` is the name of the file to load.
---@see include
---
function dofileopt(filename) end

--#endregion dofileopt
--#region iif

--TODO invalid MARKDOWN
---<h1><a href="https://premake.github.io/docs/globals/iif">iif</a></h1>
---The <strong>iif</strong> function implements an immediate "if" clause, returning one of two possible values.
---
--[[
```lua
result = iif(condition, trueval, falseval)
```
]]
---
---
---
---<h2>examples</h2>
---
--[[
```lua
result = iif(os.is("windows"), "is windows", "is not windows")
```
]]
---
---Note that all expressions are evaluated before the condition is checked; the following expression can not be implemented with an immediate if because it may try to concatenate a string value.
---
--[[
```lua
result = iif(x ~= nil, "x is " .. x, "x is nil")
```
]]
function iif() end

--#endregion iif
--#region include


---<h1><a href="https://premake.github.io/docs/globals/include">include</a></h1>
---Looks for and executes another script file, if it hasn't been run previously.
---
--[[
```lua
include("path")
```
]]
---
---
---@param path string `path` is the file system path to a script file or a directory.
---@see dofileopt
---@see includeexternal
---<h2>examples</h2>
---
--[[
```lua
-- runs "src/MyApplication/premake5.lua"
include "src/MyApplication"

-- runs "my_script.lua" just once
include "my_script.lua"
include "my_script.lua"
```
]]
function include(path) end

--#endregion include
--#region includeexternal


---<h1><a href="https://premake.github.io/docs/globals/includeexternal">includeexternal</a></h1>
---Evaluates a script, and marks any containers created by that script as external.
---
--[[
```lua
includeexternal("path")
```
]]
---
---For complex multi-workspace builds, it can be advantageous to have a set of projects that are generated by one workspace, and then used by the other workspaces as-is, without regenerating.
---
---With this function, you can include a script which may contain one or more project or rule definitions. All such containers will be marked as external, and simply referenced, but not regenerated.
---
---
---@param path string `path` is the file system path to a script file or a directory.
---@see externalproject
---@see externalrule
---@see include
---
function includeexternal(path) end

--#endregion includeexternal
--#region printf


---<h1><a href="https://premake.github.io/docs/globals/printf">printf</a></h1>
---The `printf` performs like its C counterpart, printing a formatted string.
---
--[[
```lua
printf("format", ...)
```
]]
---
---It is equivalent to this Lua code:
---
--[[
```lua
print(string.format(format, unpack(arg))
```
]]
---
---
---@param table number **format** is a formatting string containing C `printf()` style formatting codes.
---
---
function printf(table) end

--#endregion printf
--#region require


---<h1><a href="https://premake.github.io/docs/globals/require">require</a></h1>
---An extension of Lua's require() function which adds support for Premake modules and version checking.
---
--[[
```lua
require ("modname", "versions")
```
]]
---
---Premake will use its extended set of module locations when locating the requested module.
---
---
---@param list string `modname` is the name of the module to be loaded.
---@see _PREMAKE_VERSION
---<h2>examples</h2>
---
---Require Premake version 5.0 or later.
---
--[[
```lua
require("premake", ">=5.0")
```
]]
---
---If no operator is specified, defaults to ">=". I think it is a little more readable to include it though.
---
--[[
```lua
require("premake", "5.0")
```
]]
---
---Require a version 5.0 alpha 3 or later.
---
--[[
```lua
require("premake", ">=5.0.0-alpha3")
```
]]
---
---Require anything between Premake version 5.1 and 6.0.
---
--[[
```lua
require("premake", ">=5.0 <6.0")
```
]]
---
---The same rules apply to third-party modules.
---
--[[
```lua
require("foo", ">=1.1")
```
]]
function require(list) end

--#endregion require
--#region verbosef


---<h1><a href="https://premake.github.io/docs/globals/verbosef">verbosef</a></h1>
---The `verbosef` performs `printf`, printing a formatted string, but only when the <strong>verbose</strong> flag was set (ex. in the command line).
---
--[[
```lua
verbosef("format", ...)
```
]]
---
---
---@param table number **format** is a formatting string containing C `printf()` style formatting codes.
---
---
function verbosef(table) end

--#endregion verbosef